# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeworkGithubSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeworkGithubSearch
  pod 'RxSwift', '6.7.0'
  pod 'RxCocoa', '6.7.0'
 pod 'RxSwiftExt', '~> 6.0'
  pod 'SnapKit', '5.0.1'
  pod 'SDWebImage'

end
